// Known static params for the backend-driven form routes under /forms.
// output: "export" requires every dynamic path to be known at build time,
// so any new form slug/campaign path must be added here.

export const FORM_SLUGS = ['speaker', 'attendee', 'volunteer', 'speakers-2026', '6a12eba6eb565d20493de36d'];

// Campaign-style form URLs generated by the backend: /forms/{type}/{year}/{formSlug}
// e.g. https://tedxdamascus.sy/forms/Attender/2026/attendees
export const CAMPAIGN_FORM_PATHS = [
  { type: 'Attender', year: '2026', formSlug: 'attendees' },
] as const;
