import { redirect } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';
import { routing } from '@/routing';
import { GenericApiForm } from '@/components/forms/GenericApiForm';
import { CAMPAIGN_FORM_PATHS } from '@/lib/forms-routes';

// Campaign-style form URLs generated by the backend: /forms/{type}/{year}/{formSlug}
// e.g. https://tedxdamascus.sy/ar/forms/Attender/2026/attendees
//
// Only formSlug matters for rendering — it's looked up live against
// GET {baseUrl}/forms/by-slug?slug={formSlug}, and the response's targetRole
// (Attendee / Speaker / Volunteer) decides which form renders.
export function generateStaticParams() {
  return routing.locales.flatMap((locale) =>
    CAMPAIGN_FORM_PATHS.map(({ type, year, formSlug }) => ({
      locale,
      slug: type,
      year,
      formSlug,
    })),
  );
}

type Props = {
  params: Promise<{ locale: string; slug: string; year: string; formSlug: string }>;
};

// Forms are Arabic-only — any locale other than "ar" redirects to the Arabic URL
// so the whole page (nav, footer, form) renders in one consistent language.
export default async function CampaignFormPage({ params }: Props) {
  const { locale, slug, year, formSlug } = await params;
  if (locale !== 'ar') {
    redirect(`/ar/forms/${slug}/${year}/${formSlug}`);
  }
  setRequestLocale('ar');

  return <GenericApiForm formId={formSlug} locale="ar" />;
}
